tasks:
  - init: |
      docker pull gvenzl/oracle-xe
      # open the readme document for the first lab in VS code; note: thanks to the configuration in .vscode/settings.json, the document opens in markdown preview mode
  - command: |
      docker run -d -p 1521:1521 --name oracle-database-xe -e ORACLE_PASSWORD=TheSuperSecret1509! gvenzl/oracle-xe
      docker ps
      sleep 10s 
      echo "Oracle Database XE is running. The database is accessible at localhost, port 1521; database SID = XE"
      docker exec -it oracle-database-xe sqlplus sys/TheSuperSecret1509! as sysdba

ports:

  # Oracle Database XE
  - port: 1521
    onOpen: ignore
    visibility: public # this makes the database accessible from anywhere

vscode:
  extensions:
    - Oracle.oracledevtools
