tasks:
  - init: |
      docker pull gvenzl/oracle-xe
      # open the readme document for the first lab in VS code; note: thanks to the configuration in .vscode/settings.json, the document opens in markdown preview mode
      gp open README.md
  - command: |
      docker run -d -p 1521:1521 --name oracle-database-xe -e ORACLE_PASSWORD=TheSuperSecret1509! -e APP_USER=APP -e APP_USER_PASSWORD=APPPW gvenzl/oracle-xe
      sleep 2s && \
      docker ps &&  \
      echo "Oracle Database XE is running. The database is accessible at localhost, port 1521; database SID = XE and has an additional user APP/APPPW in PDB XEPDB1 " && \
      sleep 30s && \ 
      docker exec -it oracle-database-xe sqlplus sys/TheSuperSecret1509! as sysdba
  - command: |
      alias sql="/workspace/gitpod-oracle-database/sqlcl/bin/sql"
      wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip && unzip -q sqlcl-latest.zip && \
      echo "done with download and unzip SQLcl and now sleep for 90 seconds until db is running" 
      sleep 90s && /workspace/gitpod-oracle-database/sqlcl/bin/sql sys/"TheSuperSecret1509!"@localhost:1521/xe as sysdba @".prepare/create-user-dev"

ports:

  # Oracle Database XE
  - port: 1521
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - Oracle.oracledevtools
